In [1]:
import re
import networkx as nx
import pickle
import pandas as pd
import ast
from pykeen.triples import TriplesFactory
from pykeen.hpo import hpo_pipeline_from_path
from pykeen.sampling import NegativeSampler
from pykeen.pipeline import pipeline
import torch
import numpy as np

/opt/anaconda3/envs/firegnn/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
pattern_dash = r'(\w+)_HUMAN'
def gene_symbol_extractor(text, pattern:str):
        # ^ ensures start at the beginning, $ ensures end at the ')'
        match = re.search(pattern, text)
        if match:
            target = match.group(1)
            return target.upper()
        return None

In [9]:
def load_graph(filepath="../datasets/PPI_KGs/G_adni_ADKG_all.pkl"):
    with open(filepath,'rb') as f:
        ppikg = pickle.load(f)
    print(f"Load Graph with {ppikg.number_of_nodes()} nodes and {ppikg.number_of_edges()} edges.")
    return ppikg

## Get train_pos/neg edegs

In [11]:
df_adni_dual_all = pd.read_csv("../datasets/Prime_KGs/Summary_adni_dual_hybrid_all.csv", index_col=0)
df_adni_dual_all

,pos_edges_disease,neg_edges_disease,pos_edges_healthy,neg_edges_healthy,train,val,test,linked_disease_nodes,linked_healthy_nodes,label
116_S_1249,381,425,96,114,False,True,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",1
037_S_4410,310,496,66,144,False,True,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",0
006_S_4153,356,450,90,120,False,False,True,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",1
116_S_1232,411,395,125,85,True,False,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",0
128_S_0205,325,481,78,132,True,False,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",0
...,...,...,...,...,...,...,...,...,...,...
014_S_4668,405,401,110,100,True,False,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",1
130_S_0289,367,439,78,132,True,False,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",1
009_S_2381,415,391,126,84,True,False,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",1
041_S_4014,434,372,123,87,True,False,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",0
007_S_0101,418,388,124,86,True,False,False,"['AAMP', 'AATF', 'ABAT', 'ACACA', 'ACADL', 'AC...","['p(UniProtKB:""ABCA1_MOUSE"")', 'p(UniProtKB:""A...",1

In [12]:
def get_pos_neg_edges(df):
    train_pos, train_neg = [], []
    val_pos, val_neg = [], []
    test_pos, test_neg = [], [] 

    train_label_pos, train_label_neg = [], []
    val_label_pos, val_label_neg = [], []
    test_label_pos, test_label_neg = [], [] 
    # Grouping the positive and negative lists into a dictionary mapping for clean access
    splits = {
        'train': (train_pos, train_neg),
        'val': (val_pos, val_neg),
        'test': (test_pos, test_neg)
    }
    label_splits = {
        'train': (train_label_pos, train_label_neg),
        'val': (val_label_pos, val_label_neg),
        'test': (test_label_pos, test_label_neg)
    }

    for idx, row in df.iterrows():
        patient_node = idx
        
        # 1. Determine which split this row belongs to
        active_split = None
        for split_name in splits:
            if row[split_name]:
                active_split = split_name
                break
                
        if active_split is None:
            print(f"KeyError: Row {idx} does not belong to train, val, or test.")
            continue
            
        # 2. Extract lists
        disease_dst = ast.literal_eval(row['linked_disease_nodes'])
        healthy_dst = ast.literal_eval(row['linked_healthy_nodes'])
        
        # 3. Dynamically assign positive and negative target arrays based on the split
        pos_list, neg_list = splits[active_split]
        pos_label_list, neg_label_list = label_splits[active_split]
        
        # 4. Route the edges cleanly based on the label
        if row['label'] == 1:
            pos_list.extend((patient_node, 'express', dst) for dst in disease_dst)
            neg_list.extend((patient_node, 'express', dst) for dst in healthy_dst)
           
            pos_label_list.extend((patient_node, 'reg_disease', dst) for dst in disease_dst)
            neg_label_list.extend((patient_node, 'reg_disease', dst) for dst in healthy_dst)
        else:
            neg_list.extend((patient_node, 'express', dst) for dst in disease_dst)
            pos_list.extend((patient_node, 'express', dst) for dst in healthy_dst)

            neg_label_list.extend((patient_node, 'reg_healthy', dst) for dst in disease_dst)
            pos_label_list.extend((patient_node, 'reg_healthy', dst) for dst in healthy_dst)
    
    return splits, label_splits

+ (disease_sample_i, reg_disease, disease_protein)  → POSITIVE ✅
+ (disease_sample_i, reg_disease, healthy_protein)  → NEGATIVE ❌  wrong protein ----> most informative
+ (disease_sample_i, reg_healthy, disease_protein)  → NEGATIVE ❌  wrong relation
+ (disease_sample_i, reg_healthy, healthy_protein)  → NEGATIVE ❌  wrong both

In [13]:
adni_dual_all_splits, adni_dual_all_label_splits = get_pos_neg_edges(df=df_adni_dual_all)
adni_dual_all_splits

{'train': ([('116_S_1232', 'express', 'p(UniProtKB:"ABCA1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ABCA7_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ABCG1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ABCG4_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ABL1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ACTN2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ADAM9_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"AKT1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APBA1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APBA2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APBB1_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APH1A_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APH1B_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APLP1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APLP2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APOA1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APOA2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APOB_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APOE_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"APOM_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ARAF_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ARC_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"BACE1_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"BAD_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"BAG3_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"BCL2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"BDNF_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"BIN1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"BMP4_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"BRAF_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"C1QA_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CAB39_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CALR_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CARD8_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CASP3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CASP6_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CCL11_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CCL2_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CCL3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CCL5_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CCN2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CCR2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CD82_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CDC42_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CDK5_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CETP_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CLU_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CNTN2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CNTN4_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CPEB1_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CR1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CREB1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CRIP1_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CRTC2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CSF3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CSK_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CUBN_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"CUL1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"DAB1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"DAB2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"DLG4_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ECE1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ECE2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"EFNB2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"EGF_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"EGFR_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ELK1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"EOMES_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"EPHB2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ERBB4_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ERN1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"FBXL2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"FGF2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"FOS_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"FOXO1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"FOXO3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"FOXO4_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"FPR1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GAB1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GAB2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GAL_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GFAP_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GGA1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GGA2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GGA3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GHRL_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GIP_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GNA11_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GRAP2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GRB2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GRIA1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GRIA2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GRIN1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GRP_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GSK3A_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GSK3B_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"GYS1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"HMGB1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"HSPB8_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IDE_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IFNG_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IGF1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IGF1R_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL12A_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL12B_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL13_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL1A_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL1B_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL5_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IL6_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"INS_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"INSR_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IRS1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"IRS2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"JUN_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"JUND_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"KAT5_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LCAT_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LDLR_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LEP_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LIPC_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LRP1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LRP1B_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LRP2_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LRP4_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LRP5_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LRP6_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"LRP8_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"MAG_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"MBP_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"MESD_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"MTOR_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"MUSK_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"MYC_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"MYLIP_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NCAM1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NEU2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NFKB1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NGF_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NOS2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NR1H2_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NR1H3_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NR1H4_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NRCAM_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NTRK1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"NTRK2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PACS1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PAK3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PAX6_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PCSK9_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PLTP_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PON1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PPARA_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PPARG_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PPIF_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PRL_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PTBP1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PTPRA_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"PZP_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RAB5A_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RAC1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RAF1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RASA1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RASD1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RELN_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RHOA_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ROCK1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ROCK2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RRAS_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RTN4_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RTN4R_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RXRA_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RXRB_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"RXRG_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"S100B_RAT")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SCAP_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SDC2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SET_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SHBG_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SHC1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SHH_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SKP1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SMS_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SOX2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SP1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SPON1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"SRC_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"STAT3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"STK11_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"STX3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"TFCP2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"TGFB1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"TPK1_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"TPPP_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"TRPC3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"TRPC6_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"TSC2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"TTBK1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"UCHL1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"UCN2_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"UCN3_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"ULK1_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"VAMP2_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"VAMP3_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"VAMP8_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"VIP_HUMAN")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"VLDLR_MOUSE")'),
   ('116_S_1232', 'express', 'p(UniProtKB:"VPS35_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ABCA1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ABCA7_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ABCG1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ABCG4_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ABL1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ACTN2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ADAM9_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"AKT1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APBA1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APBA2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APBB1_RAT")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APH1A_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APH1B_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APLP1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APLP2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APOA1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APOA2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APOB_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APOE_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"APOM_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ARAF_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ARC_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"BACE1_RAT")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"BAD_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"BAG3_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"BCL2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"BDNF_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"BIN1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"BMP4_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"BRAF_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"C1QA_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CAB39_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CALR_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CARD8_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CASP3_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CASP6_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CCL11_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CCL2_RAT")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CCL3_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CCL5_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CCN2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CCR2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CD82_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CDC42_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CDK5_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CETP_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CLU_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CNTN2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CNTN4_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CPEB1_RAT")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CR1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CREB1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CRIP1_RAT")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CRTC2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CSF3_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CSK_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CUBN_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"CUL1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"DAB1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"DAB2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"DLG4_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ECE1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ECE2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"EFNB2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"EGF_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"EGFR_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ELK1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"EOMES_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"EPHB2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ERBB4_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"ERN1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"FBXL2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"FGF2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"FOS_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"FOXO1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"FOXO3_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"FOXO4_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"FPR1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GAB1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GAB2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GAL_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GFAP_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GGA1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GGA2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GGA3_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GHRL_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GIP_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GNA11_RAT")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GRAP2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GRB2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GRIA1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GRIA2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GRIN1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GRP_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GSK3A_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GSK3B_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"GYS1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"HMGB1_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"HSPB8_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IDE_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IFNG_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IGF1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IGF1R_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL12A_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL12B_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL13_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL1A_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL1B_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL2_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL3_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL5_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IL6_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"INS_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"INSR_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IRS1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"IRS2_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"JUN_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"JUND_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"KAT5_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LCAT_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LDLR_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LEP_RAT")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LIPC_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LRP1_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LRP1B_HUMAN")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LRP2_RAT")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LRP4_MOUSE")'),
   ('128_S_0205', 'express', 'p(UniProtKB:"LRP5_MOUSE")'),

In [14]:
adni_dual_all_label_splits

{'train': ([('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ABCA1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ABCA7_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ABCG1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ABCG4_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ABL1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ACTN2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ADAM9_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"AKT1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APBA1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APBA2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APBB1_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APH1A_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APH1B_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APLP1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APLP2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APOA1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APOA2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APOB_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APOE_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"APOM_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ARAF_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ARC_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"BACE1_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"BAD_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"BAG3_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"BCL2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"BDNF_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"BIN1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"BMP4_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"BRAF_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"C1QA_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CAB39_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CALR_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CARD8_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CASP3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CASP6_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CCL11_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CCL2_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CCL3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CCL5_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CCN2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CCR2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CD82_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CDC42_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CDK5_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CETP_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CLU_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CNTN2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CNTN4_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CPEB1_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CR1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CREB1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CRIP1_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CRTC2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CSF3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CSK_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CUBN_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"CUL1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"DAB1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"DAB2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"DLG4_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ECE1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ECE2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"EFNB2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"EGF_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"EGFR_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ELK1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"EOMES_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"EPHB2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ERBB4_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ERN1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"FBXL2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"FGF2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"FOS_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"FOXO1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"FOXO3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"FOXO4_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"FPR1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GAB1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GAB2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GAL_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GFAP_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GGA1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GGA2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GGA3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GHRL_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GIP_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GNA11_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GRAP2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GRB2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GRIA1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GRIA2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GRIN1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GRP_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GSK3A_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GSK3B_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"GYS1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"HMGB1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"HSPB8_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IDE_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IFNG_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IGF1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IGF1R_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL12A_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL12B_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL13_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL1A_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL1B_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL5_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IL6_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"INS_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"INSR_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IRS1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"IRS2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"JUN_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"JUND_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"KAT5_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LCAT_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LDLR_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LEP_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LIPC_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LRP1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LRP1B_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LRP2_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LRP4_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LRP5_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LRP6_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"LRP8_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"MAG_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"MBP_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"MESD_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"MTOR_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"MUSK_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"MYC_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"MYLIP_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NCAM1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NEU2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NFKB1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NGF_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NOS2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NR1H2_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NR1H3_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NR1H4_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NRCAM_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NTRK1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"NTRK2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PACS1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PAK3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PAX6_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PCSK9_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PLTP_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PON1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PPARA_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PPARG_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PPIF_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PRL_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PTBP1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PTPRA_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"PZP_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RAB5A_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RAC1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RAF1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RASA1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RASD1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RELN_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RHOA_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ROCK1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ROCK2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RRAS_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RTN4_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RTN4R_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RXRA_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RXRB_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"RXRG_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"S100B_RAT")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SCAP_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SDC2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SET_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SHBG_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SHC1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SHH_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SKP1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SMS_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SOX2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SP1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SPON1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"SRC_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"STAT3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"STK11_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"STX3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"TFCP2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"TGFB1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"TPK1_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"TPPP_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"TRPC3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"TRPC6_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"TSC2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"TTBK1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"UCHL1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"UCN2_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"UCN3_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"ULK1_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"VAMP2_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"VAMP3_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"VAMP8_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"VIP_HUMAN")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"VLDLR_MOUSE")'),
   ('116_S_1232', 'reg_healthy', 'p(UniProtKB:"VPS35_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ABCA1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ABCA7_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ABCG1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ABCG4_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ABL1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ACTN2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ADAM9_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"AKT1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APBA1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APBA2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APBB1_RAT")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APH1A_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APH1B_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APLP1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APLP2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APOA1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APOA2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APOB_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APOE_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"APOM_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ARAF_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ARC_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"BACE1_RAT")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"BAD_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"BAG3_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"BCL2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"BDNF_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"BIN1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"BMP4_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"BRAF_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"C1QA_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CAB39_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CALR_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CARD8_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CASP3_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CASP6_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CCL11_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CCL2_RAT")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CCL3_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CCL5_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CCN2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CCR2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CD82_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CDC42_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CDK5_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CETP_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CLU_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CNTN2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CNTN4_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CPEB1_RAT")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CR1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CREB1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CRIP1_RAT")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CRTC2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CSF3_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CSK_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CUBN_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"CUL1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"DAB1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"DAB2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"DLG4_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ECE1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ECE2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"EFNB2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"EGF_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"EGFR_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ELK1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"EOMES_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"EPHB2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ERBB4_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"ERN1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"FBXL2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"FGF2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"FOS_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"FOXO1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"FOXO3_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"FOXO4_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"FPR1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GAB1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GAB2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GAL_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GFAP_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GGA1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GGA2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GGA3_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GHRL_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GIP_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GNA11_RAT")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GRAP2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GRB2_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GRIA1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GRIA2_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GRIN1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GRP_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GSK3A_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GSK3B_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"GYS1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"HMGB1_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"HSPB8_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"IDE_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"IFNG_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"IGF1_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"IGF1R_HUMAN")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"IL12A_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"IL12B_MOUSE")'),
   ('128_S_0205', 'reg_healthy', 'p(UniProtKB:"IL13_MOUSE")'),

In [15]:
G = load_graph("../datasets/Prime_KGs/G_adni_dual_hybrid_all.pkl")

kg_triples=[]
for u, v, rel, data in G.edges(data=True, keys=True):
    
    # 1. Fast path: check if the edge key 'rel' is a valid string
    if isinstance(rel, str):
        relation = rel
    else:
        # 2. Fallback chain using dict.get() defaults
        relation = data.get('type') or data.get('relation') or data.get('rel')

    # 3. Guard against NoneType before checking 'rev'
    if relation and 'rev' not in relation:
        if u not in list(df_adni_dual_all.index):
            kg_triples.append((u, relation, v))
        else:
            if relation == 'similar':
                kg_triples.append((u, relation, v))

Load Graph with 9525 nodes and 962247 edges.

In [58]:
agnostic_triples = []

for k,v in adni_dual_all_splits.items():
    agnostic_triples.extend(v[0])
    agnostic_triples.extend(v[1])
    
train_label_triples = adni_dual_all_label_splits['train'][0]

In [60]:
agnostic_triples
train_label_triples

[('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ABCA1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ABCA7_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ABCG1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ABCG4_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ABL1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ACTN2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ADAM9_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"AKT1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APBA1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APBA2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APBB1_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APH1A_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APH1B_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APLP1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APLP2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APOA1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APOA2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APOB_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APOE_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"APOM_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ARAF_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ARC_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"BACE1_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"BAD_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"BAG3_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"BCL2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"BDNF_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"BIN1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"BMP4_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"BRAF_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"C1QA_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CAB39_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CALR_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CARD8_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CASP3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CASP6_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CCL11_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CCL2_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CCL3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CCL5_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CCN2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CCR2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CD82_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CDC42_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CDK5_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CETP_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CLU_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CNTN2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CNTN4_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CPEB1_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CR1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CREB1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CRIP1_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CRTC2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CSF3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CSK_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CUBN_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"CUL1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"DAB1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"DAB2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"DLG4_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ECE1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ECE2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"EFNB2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"EGF_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"EGFR_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ELK1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"EOMES_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"EPHB2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ERBB4_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ERN1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"FBXL2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"FGF2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"FOS_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"FOXO1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"FOXO3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"FOXO4_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"FPR1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GAB1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GAB2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GAL_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GFAP_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GGA1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GGA2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GGA3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GHRL_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GIP_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GNA11_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GRAP2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GRB2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GRIA1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GRIA2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GRIN1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GRP_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GSK3A_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GSK3B_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"GYS1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"HMGB1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"HSPB8_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IDE_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IFNG_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IGF1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IGF1R_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL12A_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL12B_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL13_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL1A_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL1B_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL5_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IL6_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"INS_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"INSR_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IRS1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"IRS2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"JUN_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"JUND_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"KAT5_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LCAT_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LDLR_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LEP_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LIPC_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LRP1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LRP1B_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LRP2_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LRP4_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LRP5_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LRP6_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"LRP8_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"MAG_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"MBP_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"MESD_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"MTOR_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"MUSK_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"MYC_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"MYLIP_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NCAM1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NEU2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NFKB1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NGF_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NOS2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NR1H2_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NR1H3_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NR1H4_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NRCAM_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NTRK1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"NTRK2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PACS1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PAK3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PAX6_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PCSK9_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PLTP_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PON1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PPARA_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PPARG_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PPIF_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PRL_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PTBP1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PTPRA_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"PZP_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RAB5A_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RAC1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RAF1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RASA1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RASD1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RELN_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RHOA_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ROCK1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ROCK2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RRAS_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RTN4_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RTN4R_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RXRA_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RXRB_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"RXRG_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"S100B_RAT")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SCAP_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SDC2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SET_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SHBG_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SHC1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SHH_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SKP1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SMS_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SOX2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SP1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SPON1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"SRC_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"STAT3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"STK11_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"STX3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"TFCP2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"TGFB1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"TPK1_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"TPPP_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"TRPC3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"TRPC6_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"TSC2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"TTBK1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"UCHL1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"UCN2_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"UCN3_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"ULK1_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"VAMP2_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"VAMP3_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"VAMP8_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"VIP_HUMAN")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"VLDLR_MOUSE")'),
 ('037_S_4410', 'reg_healthy', 'p(UniProtKB:"VPS35_HUMAN")'),
 ('006_S_4153', 'reg_disease', 'AAMP'),
 ('006_S_4153', 'reg_disease', 'AATF'),
 ('006_S_4153', 'reg_disease', 'ABAT'),
 ('006_S_4153', 'reg_disease', 'ACACA'),
 ('006_S_4153', 'reg_disease', 'ACADL'),
 ('006_S_4153', 'reg_disease', 'ACADVL'),
 ('006_S_4153', 'reg_disease', 'ACE'),
 ('006_S_4153', 'reg_disease', 'ACHE'),
 ('006_S_4153', 'reg_disease', 'ACLY'),
 ('006_S_4153', 'reg_disease', 'ACTB'),
 ('006_S_4153', 'reg_disease', 'ADA'),
 ('006_S_4153', 'reg_disease', 'ADIPOQ'),
 ('006_S_4153', 'reg_disease', 'ADIRF'),
 ('006_S_4153', 'reg_disease', 'AFDN'),
 ('006_S_4153', 'reg_disease', 'AFP'),
 ('006_S_4153', 'reg_disease', 'AGER'),
 ('006_S_4153', 'reg_disease', 'AGRN'),
 ('006_S_4153', 'reg_disease', 'AGT'),
 ('006_S_4153', 'reg_disease', 'AGTRAP'),
 ('006_S_4153', 'reg_disease', 'AHNAK'),
 ('006_S_4153', 'reg_disease', 'AHR'),
 ('006_S_4153', 'reg_disease', 'AHRR'),
 ('006_S_4153', 'reg_disease', 'AHSG'),
 ('006_S_4153', 'reg_disease', 'AICDA'),
 ('006_S_4153', 'reg_disease', 'AKNA'),
 ('006_S_4153', 'reg_disease', 'AKTIP'),
 ('006_S_4153', 'reg_disease', 'ALAD'),
 ('006_S_4153', 'reg_disease', 'ALB'),
 ('006_S_4153', 'reg_disease', 'ALDOA'),
 ('006_S_4153', 'reg_disease', 'ALDOB'),
 ('006_S_4153', 'reg_disease', 'ALPL'),
 ('006_S_4153', 'reg_disease', 'ALPP'),
 ('006_S_4153', 'reg_disease', 'ALYREF'),
 ('006_S_4153', 'reg_disease', 'AMBP'),
 ('006_S_4153', 'reg_disease', 'AMFR'),
 ('006_S_4153', 'reg_disease', 'AMOT'),
 ('006_S_4153', 'reg_disease', 'AMPH'),
 ('006_S_4153', 'reg_disease', 'ANKAR'),
 ('006_S_4153', 'reg_disease', 'ANKH'),
 ('006_S_4153', 'reg_disease', 'ANLN'),
 ('006_S_4153', 'reg_disease', 'APC'),
 ('006_S_4153', 'reg_disease', 'APLF'),
 ('006_S_4153', 'reg_disease', 'APOD'),
 ('006_S_4153', 'reg_disease', 'APOE'),
 ('006_S_4153', 'reg_disease', 'APP'),
 ('006_S_4153', 'reg_disease', 'APRT'),
 ('006_S_4153', 'reg_disease', 'AR'),
 ('006_S_4153', 'reg_disease', 'ARC'),
 ('006_S_4153', 'reg_disease', 'AREG'),
 ('006_S_4153', 'reg_disease', 'ARHGDIA'),
 ('006_S_4153', 'reg_disease', 'ARHGDIB'),
 ('006_S_4153', 'reg_disease', 'ARNT'),
 ('006_S_4153', 'reg_disease', 'ARNTL'),
 ('006_S_4153', 'reg_disease', 'ARSG'),
 ('006_S_4153', 'reg_disease', 'ARVCF'),
 ('006_S_4153', 'reg_disease', 'ASL'),
 ('006_S_4153', 'reg_disease', 'ASPH'),
 ('006_S_4153', 'reg_disease', 'ATM'),
 ('006_S_4153', 'reg_disease', 'AURKA'),
 ('006_S_4153', 'reg_disease', 'AVEN'),
 ('006_S_4153', 'reg_disease', 'AVP'),
 ('006_S_4153', 'reg_disease', 'AXL'),
 ('006_S_4153', 'reg_disease', 'BAD'),
 ('006_S_4153', 'reg_disease', 'BAMBI'),
 ('006_S_4153', 'reg_disease', 'BANP'),
 ('006_S_4153', 'reg_disease', 'BAX'),
 ('006_S_4153', 'reg_disease', 'BBX'),
 ('006_S_4153', 'reg_disease', 'BCAM'),
 ('006_S_4153', 'reg_disease', 'BCCIP'),
 ('006_S_4153', 'reg_disease', 'BCHE'),
 ('006_S_4153', 'reg_disease', 'BCKDK'),
 ('006_S_4153', 'reg_disease', 'BCOR'),
 ('006_S_4153', 'reg_disease', 'BCR'),
 ('006_S_4153', 'reg_disease', 'BDNF'),
 ('006_S_4153', 'reg_disease', 'BFAR'),
 ('006_S_4153', 'reg_disease', 'BGN'),
 ('006_S_4153', 'reg_disease', 'BICRAL'),
 ('006_S_4153', 'reg_disease', 'BID'),
 ('006_S_4153', 'reg_disease', 'BIK'),
 ('006_S_4153', 'reg_disease', 'BLCAP'),
 ('006_S_4153', 'reg_disease', 'BLID'),
 ('006_S_4153', 'reg_disease', 'BLK'),
 ('006_S_4153', 'reg_disease', 'BLM'),
 ('006_S_4153', 'reg_disease', 'BLMH'),
 ('006_S_4153', 'reg_disease', 'BLNK'),
 ('006_S_4153', 'reg_disease', 'BLVRA'),
 ('006_S_4153', 'reg_disease', 'BMF'),
 ('006_S_4153', 'reg_disease', 'BMX'),
 ('006_S_4153', 'reg_disease', 'BNIPL'),
 ('006_S_4153', 'reg_disease', 'BORA'),
 ('006_S_4153', 'reg_disease', 'BRDT'),
 ('006_S_4153', 'reg_disease', 'BSG'),
 ('006_S_4153', 'reg_disease', 'BTK'),
 ('006_S_4153', 'reg_disease', 'BTRC'),
 ('006_S_4153', 'reg_disease', 'BYSL'),
 ('006_S_4153', 'reg_disease', 'CABYR'),
 ('006_S_4153', 'reg_disease', 'CACYBP'),
 ('006_S_4153', 'reg_disease', 'CAD'),
 ('006_S_4153', 'reg_disease', 'CALR'),
 ('006_S_4153', 'reg_disease', 'CALY'),
 ('006_S_4153', 'reg_disease', 'CAMLG'),
 ('006_S_4153', 'reg_disease', 'CAMP'),
 ('006_S_4153', 'reg_disease', 'CANX'),
 ('006_S_4153', 'reg_disease', 'CAPZB'),
 ('006_S_4153', 'reg_disease', 'CARF'),
 ('006_S_4153', 'reg_disease', 'CAT'),
 ('006_S_4153', 'reg_disease', 'CBFB'),
 ('006_S_4153', 'reg_disease', 'CBL'),
 ('006_S_4153', 'reg_disease', 'CBLB'),
 ('006_S_4153', 'reg_disease', 'CBLC'),
 ('006_S_4153', 'reg_disease', 'CCK'),
 ('006_S_4153', 'reg_disease', 'CCNH'),
 ('006_S_4153', 'reg_disease', 'CDSN'),
 ('006_S_4153', 'reg_disease', 'CDYL'),
 ('006_S_4153', 'reg_disease', 'CEBPA'),
 ('006_S_4153', 'reg_disease', 'CEBPB'),
 ('006_S_4153', 'reg_disease', 'CEBPD'),
 ('006_S_4153', 'reg_disease', 'CEBPG'),
 ('006_S_4153', 'reg_disease', 'CEBPZ'),
 ('006_S_4153', 'reg_disease', 'CENPB'),
 ('006_S_4153', 'reg_disease', 'CENPQ'),
 ('006_S_4153', 'reg_disease', 'CENPT'),
 ('006_S_4153', 'reg_disease', 'CENPU'),
 ('006_S_4153', 'reg_disease', 'CFI'),
 ('006_S_4153', 'reg_disease', 'CFLAR'),
 ('006_S_4153', 'reg_disease', 'CFTR'),
 ('006_S_4153', 'reg_disease', 'CHAT'),
 ('006_S_4153', 'reg_disease', 'CHGB'),
 ('006_S_4153', 'reg_disease', 'CHKA'),
 ('006_S_4153', 'reg_disease', 'CHUK'),
 ('006_S_4153', 'reg_disease', 'CIDEB'),
 ('006_S_4153', 'reg_disease', 'CIITA'),
 ('006_S_4153', 'reg_disease', 'CILP'),
 ('006_S_4153', 'reg_disease', 'CIRBP'),
 ('006_S_4153', 'reg_disease', 'CISH'),
 ('006_S_4153', 'reg_disease', 'CLNK'),
 ('006_S_4153', 'reg_disease', 'CLOCK'),
 ('006_S_4153', 'reg_disease', 'CLPB'),
 ('006_S_4153', 'reg_disease', 'CLTA'),
 ('006_S_4153', 'reg_disease', 'CLTB'),
 ('006_S_4153', 'reg_disease', 'CLTC'),
 ('006_S_4153', 'reg_disease', 'CLU'),
 ('006_S_4153', 'reg_disease', 'CLYBL'),
 ('006_S_4153', 'reg_disease', 'CMAS'),
 ('006_S_4153', 'reg_disease', 'CNP'),
 ('006_S_4153', 'reg_disease', 'CNTF'),
 ('006_S_4153', 'reg_disease', 'CNTRL'),
 ('006_S_4153', 'reg_disease', 'COASY'),
 ('006_S_4153', 'reg_disease', 'COIL'),
 ('006_S_4153', 'reg_disease', 'COLQ'),
 ('006_S_4153', 'reg_disease', 'COMT'),
 ('006_S_4153', 'reg_disease', 'COPA'),
 ('006_S_4153', 'reg_disease', 'CP'),
 ('006_S_4153', 'reg_disease', 'CPD'),
 ('006_S_4153', 'reg_disease', 'CPE'),
 ('006_S_4153', 'reg_disease', 'CRADD'),
 ('006_S_4153', 'reg_disease', 'CREBBP'),
 ('006_S_4153', 'reg_disease', 'CREM'),
 ('006_S_4153', 'reg_disease', 'CRH'),
 ('006_S_4153', 'reg_disease', 'CRK'),
 ('006_S_4153', 'reg_disease', 'CRKL'),
 ('006_S_4153', 'reg_disease', 'CRP'),
 ('006_S_4153', 'reg_disease', 'CRX'),
 ('006_S_4153', 'reg_disease', 'CRYAA'),
 ('006_S_4153', 'reg_disease', 'CRYAB'),
 ('006_S_4153', 'reg_disease', 'CS'),
 ('006_S_4153', 'reg_disease', 'CSAD'),
 ('006_S_4153', 'reg_disease', 'CSK'),
 ('006_S_4153', 'reg_disease', 'CSTB'),
 ('006_S_4153', 'reg_disease', 'CTCF'),
 ('006_S_4153', 'reg_disease', 'CTH'),
 ('006_S_4153', 'reg_disease', 'CTSB'),
 ('006_S_4153', 'reg_disease', 'CTSD'),
 ('006_S_4153', 'reg_disease', 'CTSE'),
 ('006_S_4153', 'reg_disease', 'CTSS'),
 ('006_S_4153', 'reg_disease', 'CTTN'),
 ('006_S_4153', 'reg_disease', 'CUBN'),
 ('006_S_4153', 'reg_disease', 'CYCS'),

## Train PyKEEN

In [65]:
train_triples = np.concatenate([
    kg_triples,
    agnostic_triples,       # includes val/test sample nodes → they get embeddings
    train_label_triples,    # only train samples' positive label edges
], axis=0)

tf_train = TriplesFactory.from_labeled_triples(
    triples=train_triples,
    create_inverse_triples=True,
)

# --- Run KGE ---
ratios = [0.8, 0.1, 0.1]
train, test, val = tf_train.split(ratios, random_state=42)

config_file = "../PyKeen/configs/RotatE_config_hpo.json"  
print(f"\n--- Running HPO---\n")
hpo_result = hpo_pipeline_from_path(
    config_file, 
    training = train, 
    testing=test, 
    validation=val
    )

[I 2026-05-26 17:23:28,099] A new study created in memory with name: no-name-61c7c894-a47f-4d30-a574-b40329fbd887
/home/xyu/.conda/envs/firegnn/lib/python3.11/site-packages/optuna/distributions.py:671: UserWarning: The distribution is specified by [1, 20] and step=5.0, but the range is not divisible by `step`. It will be replaced with [1, 16.0].
  optuna_warn(
/home/xyu/.conda/envs/firegnn/lib/python3.11/site-packages/optuna/distributions.py:671: UserWarning: The distribution is specified by [0.1, 1.0] and step=0.5, but the range is not divisible by `step`. It will be replaced with [0.1, 0.6].
  optuna_warn(
/home/xyu/.conda/envs/firegnn/lib/python3.11/site-packages/optuna/distributions.py:684: UserWarning: The distribution is specified by [1, 50] and step=10, but the range is not divisible by `step`. It will be replaced with [1, 41].
  optuna_warn(
No random seed is specified. Setting to 1682555331.

--- Running HPO---

INFO:pykeen.triples.triples_factory:Creating inverse triples.
Training epochs on cuda:0:   0%|          | 0/100 [00:00<?, ?epoch/s]INFO:pykeen.triples.triples_factory:Creating inverse triples.
Training epochs on cuda:0:  24%|██▍       | 24/100 [19:42<1:03:50, 50.40s/epoch, loss=5.54, prev_loss=5.54]INFO:pykeen.evaluation.evaluator:Evaluation took 87.99s seconds
INFO:pykeen.stoppers.early_stopping:New best result at epoch 25: 0.013673112311080274. Saved model weights to /home/xyu/.data/pykeen/checkpoints/best-model-weights-53a5b1dc-e71c-46f6-9001-183caa13c3f6.pt
INFO:pykeen.training.training_loop:=> Saved checkpoint after having finished epoch 25.
Training epochs on cuda:0:  49%|████▉     | 49/100 [38:04<34:43, 40.86s/epoch, loss=5.54, prev_loss=5.54]  INFO:pykeen.evaluation.evaluator:Evaluation took 114.16s seconds
Training epochs on cuda:0:  74%|███████▍  | 74/100 [1:00:16<23:49, 55.00s/epoch, loss=5.54, prev_loss=5.54]INFO:pykeen.evaluation.evaluator:Evaluation took 117.19s seconds
Training epochs on cuda:0:  99%|█████████▉| 99/100 [1:24:35<00:49, 49.52s/epoch, loss=5.54, prev_loss=5.54]INFO:pykeen.evaluation.evaluator:Evaluation took 129.57s seconds
Training epochs on cuda:0: 100%|██████████| 100/100 [1:26:45<00:00, 52.05s/epoch, loss=5.54, prev_loss=5.54]
Evaluating on cuda:0: 100%|██████████| 66.3k/66.3k [02:07<00:00, 518triple/s]
INFO:pykeen.evaluation.evaluator:Evaluation took 128.92s seconds
[I 2026-05-26 18:52:24,477] Trial 0 finished with value: 0.012029020483272496 and parameters: {'model.embedding_dim': 256, 'loss.margin': 11.0, 'loss.adversarial_temperature': 0.1, 'optimizer.lr': 0.45383915072637565, 'negative_sampler.num_negs_per_pos': 11, 'training.batch_size': 256}. Best is trial 0 with value: 0.012029020483272496.

In [77]:
hpo_result.save_to_directory("../PyKeen/results/dual_kg")

In [80]:
import pandas as pd
from pykeen.predict import predict_target, predict_triples
from pykeen.pipeline import pipeline_from_path

# 2. RETRAIN THE MODEL WITH BEST PARAMETERS
print("\n--- Retraining Best Model Configuration ---")

pipeline_config = "../PyKeen/results/dual_kg/best_pipeline/pipeline_config.json"
best_pipeline_result = pipeline_from_path(
    pipeline_config,
    training=train,
    testing=test,
    validation=val
)

WARNING:pykeen.pipeline.api:No random seed is specified. Setting to 505895154.
INFO:pykeen.pipeline.api:Using device: None
INFO:pykeen.nn.representation:Inferred unique=False for Embedding(
  (regularizer): NoRegularizer()
)
INFO:pykeen.nn.representation:Inferred unique=False for Embedding()
INFO:pykeen.triples.triples_factory:Creating inverse triples.

--- Retraining Best Model Configuration ---

Training epochs on cuda:0:   0%|          | 0/10 [00:00<?, ?epoch/s]INFO:pykeen.triples.triples_factory:Creating inverse triples.
Training epochs on cuda:0: 100%|██████████| 10/10 [08:05<00:00, 48.56s/epoch, loss=5.56, prev_loss=5.54]
Evaluating on cuda:0: 100%|██████████| 66.3k/66.3k [01:21<00:00, 814triple/s]
INFO:pykeen.evaluation.evaluator:Evaluation took 82.51s seconds

In [81]:
best_model = best_pipeline_result.model
best_pipeline_result.save_to_directory("../PyKeen/results/dual_kg")

INFO:pykeen.triples.triples_factory:Stored TriplesFactory(num_entities=9511, num_relations=86, create_inverse_triples=True, num_triples=530381) to file:///home/xyu/thesis/HybridKG/PyKeen/results/dual_kg/training_triples
INFO:pykeen.pipeline.api:Saved to directory: /home/xyu/thesis/HybridKG/PyKeen/results/dual_kg

In [90]:
import json
from pathlib import Path
from pykeen.pipeline import pipeline_from_config


pipeline_config = json.loads(
    Path("../PyKeen/results/dual_kg/best_pipeline/pipeline_config.json").read_text()
    )
pipeline_config['pipeline']['training']=train
pipeline_config['pipeline']['testing']=test
pipeline_config['pipeline']['validation']=val

best_pipeline_result = pipeline_from_config(pipeline_config)

WARNING:pykeen.pipeline.api:No random seed is specified. Setting to 692413693.
INFO:pykeen.pipeline.api:Using device: None
INFO:pykeen.nn.representation:Inferred unique=False for Embedding(
  (regularizer): NoRegularizer()
)
INFO:pykeen.nn.representation:Inferred unique=False for Embedding()
INFO:pykeen.triples.triples_factory:Creating inverse triples.
Training epochs on cuda:0:   0%|          | 0/10 [00:00<?, ?epoch/s]INFO:pykeen.triples.triples_factory:Creating inverse triples.
Training epochs on cuda:0:   0%|          | 0/10 [00:05<?, ?epoch/s]

KeyboardInterrupt:

In [84]:
# 3. LINK PREDICTION

print("\n--- Running Link Prediction Workflows ---")
candidate_triples = np.concatenate([adni_dual_all_label_splits['val'][0],
                                    adni_dual_all_label_splits['val'][1],
                                    adni_dual_all_label_splits['test'][0],
                                    adni_dual_all_label_splits['test'][1],
                                    ],axis=0)

# Scores the specific combinations
scored_pack = predict_triples(
    model=best_model, 
    triples=candidate_triples, 
    triples_factory=train
)
# Convert the scored pack to a readable Pandas DataFrame
predictions_df = scored_pack.process(factory=train).df
print("\nScores for specific candidate triples:")
predictions_df

WARNING:torch_max_mem.api:Encountered tensors on device_types={'cpu'} while only ['cuda'] are considered safe for automatic memory utilization maximization. This may lead to undocumented crashes (but can be safe, too).

--- Running Link Prediction Workflows ---

Scores for specific candidate triples:

,head_id,head_label,relation_id,relation_label,tail_id,tail_label,score
0,0,002_S_0413,38,reg_healthy,456,AAMP,-19.100306
1,0,002_S_0413,38,reg_healthy,458,AATF,-23.603207
2,0,002_S_0413,38,reg_healthy,459,ABAT,-16.800436
3,0,002_S_0413,38,reg_healthy,482,ACACA,-12.660259
4,0,002_S_0413,38,reg_healthy,485,ACADL,-18.646162
...,...,...,...,...,...,...,...
139187,451,941_S_4292,38,reg_healthy,8527,"p(UniProtKB:""VAMP3_HUMAN"")",-11.282839
139188,451,941_S_4292,38,reg_healthy,8530,"p(UniProtKB:""VAMP8_HUMAN"")",-16.731258
139189,451,941_S_4292,38,reg_healthy,8537,"p(UniProtKB:""VIP_HUMAN"")",-18.566980
139190,451,941_S_4292,38,reg_healthy,8541,"p(UniProtKB:""VLDLR_MOUSE"")",-12.849744
139191,451,941_S_4292,38,reg_healthy,8544,"p(UniProtKB:""VPS35_HUMAN"")",-22.918825

In [86]:
sample_label_map = df_adni_dual_all['label'].to_dict()
predictions_df['true_labels'] = predictions_df['head_label'].map(sample_label_map)
predictions_df

,head_id,head_label,relation_id,relation_label,tail_id,tail_label,score,true_labels
0,0,002_S_0413,38,reg_healthy,456,AAMP,-19.100306,0
1,0,002_S_0413,38,reg_healthy,458,AATF,-23.603207,0
2,0,002_S_0413,38,reg_healthy,459,ABAT,-16.800436,0
3,0,002_S_0413,38,reg_healthy,482,ACACA,-12.660259,0
4,0,002_S_0413,38,reg_healthy,485,ACADL,-18.646162,0
...,...,...,...,...,...,...,...,...
139187,451,941_S_4292,38,reg_healthy,8527,"p(UniProtKB:""VAMP3_HUMAN"")",-11.282839,0
139188,451,941_S_4292,38,reg_healthy,8530,"p(UniProtKB:""VAMP8_HUMAN"")",-16.731258,0
139189,451,941_S_4292,38,reg_healthy,8537,"p(UniProtKB:""VIP_HUMAN"")",-18.566980,0
139190,451,941_S_4292,38,reg_healthy,8541,"p(UniProtKB:""VLDLR_MOUSE"")",-12.849744,0
139191,451,941_S_4292,38,reg_healthy,8544,"p(UniProtKB:""VPS35_HUMAN"")",-22.918825,0

In [88]:
predictions_df[predictions_df['relation_label']=="reg_healthy"]

,head_id,head_label,relation_id,relation_label,tail_id,tail_label,score,true_labels
0,0,002_S_0413,38,reg_healthy,456,AAMP,-19.100306,0
1,0,002_S_0413,38,reg_healthy,458,AATF,-23.603207,0
2,0,002_S_0413,38,reg_healthy,459,ABAT,-16.800436,0
3,0,002_S_0413,38,reg_healthy,482,ACACA,-12.660259,0
4,0,002_S_0413,38,reg_healthy,485,ACADL,-18.646162,0
...,...,...,...,...,...,...,...,...
139187,451,941_S_4292,38,reg_healthy,8527,"p(UniProtKB:""VAMP3_HUMAN"")",-11.282839,0
139188,451,941_S_4292,38,reg_healthy,8530,"p(UniProtKB:""VAMP8_HUMAN"")",-16.731258,0
139189,451,941_S_4292,38,reg_healthy,8537,"p(UniProtKB:""VIP_HUMAN"")",-18.566980,0
139190,451,941_S_4292,38,reg_healthy,8541,"p(UniProtKB:""VLDLR_MOUSE"")",-12.849744,0
139191,451,941_S_4292,38,reg_healthy,8544,"p(UniProtKB:""VPS35_HUMAN"")",-22.918825,0

In [91]:
predictions_df.to_csv("../PyKeen/results/dual_kg/link_predictions.csv")